version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=urlmapping'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - '5435:5432'
    networks:
      - urlmapping_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  urlmapping_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
