version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: urlmapping
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - urlmapping_network

  urlmapping-app:
    build: .
    container_name: urlmapping-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/urlmapping
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - urlmapping_network

networks:
  urlmapping_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
