spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/urlmapping_test
    username: root
    password: root
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
     ddl-auto: update

  feign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000
  logging:
    level:
      org.springframework.cloud.openfeign: DEBUG
