spring:
  datasource:
    url: postgres://root:root@localhost:5433/urlmapping
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  feign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000
  logging:
    level:
      org.springframework.cloud.openfeign: DEBUG
